name: leetcode
description: LeetCode Dart solutions
version: 0.0.1-dev
repository: https://github.com/PlugFox/leetcode
issue_tracker: https://github.com/PlugFox/leetcode/issues
homepage: https://github.com/PlugFox/leetcode

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
  coverage: any
